### ISSUE TITLE
Move to other organization?

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/BlueStyle#117]
Invenia is less active than it used to be, maybe the BlueStyle would be more at home somewhere else?

**Comment by iamed2** [comment]
Yup, do you have a suggestion? Is another organization heavily using BlueStyle in its repos?

**Comment by gdalle** [comment]
@oxinabox suggested JuliaDiff

**Comment by iamed2** [comment]
Fine by me, and she has the requisite GitHub permissions to do that (I do not) 👍

**Comment by oxinabox** [comment]
I don't feel a strong urge to moving it.
But I am willing to be convinced.
It is kinda a static document it doesn't tend to need changes.

**Comment by gdalle** [comment]
My main argument is that users might be deterred to chose this style guide because it belongs to an inactive organization, as opposed to SciML's. And I really don't like SciML's 😅

**Comment by oxinabox** [comment]
ok, I am sold
